// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE


var constantsState = /* record */[
  /* windowHeight */256,
  /* windowWidth */512,
  /* memberLength */5,
  /* memberWidth */3
];

export {
  constantsState ,
  
}
/* No side effect */
