// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE

import * as Game from "./game/Game.bs.js";
import * as ReactDOMRe from "./../../../node_modules/reason-react/lib/es6_global/src/ReactDOMRe.js";
import * as ReasonReact from "./../../../node_modules/reason-react/lib/es6_global/src/ReasonReact.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Game.make(/* array */[])), "game");

export {
  
}
/*  Not a pure module */
