// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE

import * as List from "./../../../node_modules/bs-platform/lib/es6/list.js";
import * as Utils from "./Utils.bs.js";

function map_eaten_to_score(enemies) {
  return List.map((function (x) {
                if (typeof x === "number") {
                  return 0;
                } else if (x.tag) {
                  return 50;
                } else {
                  return 10;
                }
              }), enemies);
}

function sum_score(enemies) {
  return List.fold_left(Utils.Utils[/* sum */6], 0, map_eaten_to_score(enemies));
}

var Score = /* module */[
  /* map_eaten_to_score */map_eaten_to_score,
  /* sum_score */sum_score
];

export {
  Score ,
  
}
/* No side effect */
