// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE

import * as List from "./../../../node_modules/bs-platform/lib/es6/list.js";
import * as Curry from "./../../../node_modules/bs-platform/lib/es6/curry.js";

function add(a, b) {
  return a + b | 0;
}

function inc(i) {
  return i + 1 | 0;
}

function dec(i) {
  return i - 1 | 0;
}

function $$double(i) {
  return (i << 1);
}

function incDouble(i) {
  return ((i + 1 | 0) << 1);
}

function sub(a, b) {
  return a - b | 0;
}

var Utils = /* module */[
  /* add */add,
  /* inc */inc,
  /* dec */dec,
  /* double */$$double,
  /* incDouble */incDouble,
  /* sub */sub
];

function map(f, param) {
  if (param) {
    return /* :: */[
            Curry._1(f, param[0]),
            map(f, param[1])
          ];
  } else {
    return /* [] */0;
  }
}

function forEach(f, _param) {
  while(true) {
    var param = _param;
    if (param) {
      Curry._1(f, param[0]);
      _param = param[1];
      continue ;
    } else {
      return /* () */0;
    }
  };
}

function forEachi(f, l) {
  var _i = 0;
  var _param = l;
  while(true) {
    var param = _param;
    var i = _i;
    if (param) {
      Curry._2(f, param[0], i);
      _param = param[1];
      _i = i + 1 | 0;
      continue ;
    } else {
      return /* () */0;
    }
  };
}

function range(n) {
  var inner = function (_acc, _i) {
    while(true) {
      var i = _i;
      var acc = _acc;
      if (i !== 0) {
        _i = i - 1 | 0;
        _acc = /* :: */[
          i,
          acc
        ];
        continue ;
      } else {
        return acc;
      }
    };
  };
  return List.rev(inner(/* [] */0, n));
}

var MyList = /* module */[
  /* map */map,
  /* forEach */forEach,
  /* forEachi */forEachi,
  /* range */range
];

export {
  Utils ,
  MyList ,
  
}
/* No side effect */
