// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE


var constantsState = /* record */[
  /* windowHeight */768,
  /* windowWidth */1536,
  /* memberLength */5,
  /* memberWidth */10,
  /* tileSize */96
];

export {
  constantsState ,
  
}
/* No side effect */
